### ISSUE TITLE
make sure that jax is not required by default

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/pyepal#153]
## Steps to reproduce the problem

Did install the master from github without any extras and wanted to use some GPy based model and ran into the following issue. 

```
▽
  1 /home/kjablonk/anaconda3/envs/pypal/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in versio    n 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  2   warnings.warn(message, FutureWarning)
  3 warning in stationary: failed to import cython module: falling back to numpy
  4 warning in coregionalize: failed to import cython module: falling back to numpy
  5 warning in choleskies: failed to import cython module: falling back to numpy
  6 Traceback (most recent call last):
  7   File "run_pal_on_dispersant_repeats_cli.py", line 36, in <module>
  8     from pyepal import PALCoregionalized
  9   File "/home/kjablonk/anaconda3/envs/pypal/lib/python3.7/site-packages/pyepal/__init__.py", line 19, in <module>
 10     from .models.nt import JaxOptimizer, NTModel
 11   File "/home/kjablonk/anaconda3/envs/pypal/lib/python3.7/site-packages/pyepal/models/nt.py", line 34, in <module>
 12     from jax import jit
 13 ModuleNotFoundError: No module named 'jax'
~
```
Probably we need to move the import into the functions 

## Specifications

- pyepal version: 0.4.2+15.g4a49b71

**Comment by kjappelbaum** [comment]
Missed one instance 

```
(pypal) [kjablonk@fidis parameter_sweep]$ cat slurm-6673018.out
/home/kjablonk/anaconda3/envs/pypal/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)
warning in stationary: failed to import cython module: falling back to numpy
warning in coregionalize: failed to import cython module: falling back to numpy
warning in choleskies: failed to import cython module: falling back to numpy
Traceback (most recent call last):
  File "run_pal_on_dispersant_repeats_cli.py", line 36, in <module>
    from pyepal import PALCoregionalized
  File "/home/kjablonk/anaconda3/envs/pypal/lib/python3.7/site-packages/pyepal/__init__.py", line 22, in <module>
    from .pal.pal_finite_ensemble import PALJaxEnsemble
  File "/home/kjablonk/anaconda3/envs/pypal/lib/python3.7/site-packages/pyepal/pal/pal_finite_ensemble.py", line 24, in <module>
    from jax import random
ModuleNotFoundError: No module named 'jax'
```

**Comment by kjappelbaum** [comment]
just installed in a clean conda env and didn't throw the error
